//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcClase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int cod_producto { get; set; }
        public string nom_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado_activo { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<System.DateTime> fec_caducidad { get; set; }
        public Nullable<decimal> precio_compra { get; set; }
        public Nullable<int> cod_proveedor { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
