//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcClase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int cod_usuario { get; set; }
        public string nom_usuario { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string correo_electronico { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<int> estado_activo { get; set; }
    }
}
